name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'

version: 1.3.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.1
  connectivity: ^3.0.3
  dio: ^4.0.0-prev2
  http: ^0.13.1
  freezed: ^0.14.1
  shared_preferences: ^2.0.5
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  image_picker: ^0.7.3
  webview_flutter: ^2.0.2
  flutter_html: ^2.0.0-nullsafety.0
  share: ^2.0.1
  photo_view: ^0.13.0
  package_info: ^2.0.0
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.1
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^3.5.1
  flutter_svg: ^0.22.0
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.0.0
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.0
  geolocator: ^8.0.1
  flutter_typeahead: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
